version: '3.8'

services:

  # Service for the MySQL database
  mysql-db:
    image: mysql:8.4.3  # Use 8.4.3 because support for mysql_native_password has been removed in 9.*
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: atlassiandemodb
      MYSQL_USER: app
      MYSQL_PASSWORD: password
      MYSQL_AUTHENTICATION_PLUGIN: mysql_native_password
    command: "--mysql-native-password=ON"
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"   # Expose MySQL port 3306
    networks:
      - aspnetcore-mysql-network

# Define the volume for MySQL data persistence
volumes:
  mysql-data:

# Define the network to connect both services
networks:
  aspnetcore-mysql-network:
    driver: bridge

